server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # SPA routing — all routes go to index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy API calls to Gateway
    location /identity/ {
        proxy_pass http://gateway-service.shopflow.svc.cluster.local/identity/;
        proxy_set_header Host $host;
        proxy_set_header Authorization $http_authorization;
    }

    location /inventory/ {
        proxy_pass http://gateway-service.shopflow.svc.cluster.local/inventory/;
        proxy_set_header Host $host;
        proxy_set_header Authorization $http_authorization;
    }

    location /orders/ {
        proxy_pass http://gateway-service.shopflow.svc.cluster.local/orders/;
        proxy_set_header Host $host;
        proxy_set_header Authorization $http_authorization;
    }

    # Cache static assets
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}