apiVersion: v1
kind: Secret
metadata:
  name: orders-secret
  namespace: shopflow
type: Opaque
stringData:
  CONNECTION_STRING: "Server=sql-service.shopflow.svc.cluster.local,1433;Database=ShopFlow.Orders;User Id=sa;Password=Swiss@1991;TrustServerCertificate=True"
  JWT_KEY: "Bpmqwe23@$^5lkj+nxGVY7jfiYX%klIveHFt8pRYw7MtNmLg1hqlcG7J8i1+5HKV9vw"