apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-api
  namespace: shopflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-api
  template:
    metadata:
      labels:
        app: orders-api
    spec:
      containers:
        - name: orders-api
          image: shopflow-orders:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: orders-secret
                  key: CONNECTION_STRING
            - name: Jwt__Key
              valueFrom:
                secretKeyRef:
                  name: orders-secret
                  key: JWT_KEY
            - name: Jwt__Issuer
              valueFrom:
                configMapKeyRef:
                  name: orders-config
                  key: JWT_ISSUER
            - name: Jwt__Audience
              valueFrom:
                configMapKeyRef:
                  name: orders-config
                  key: JWT_AUDIENCE
            - name: Kafka__BootstrapServers
              valueFrom:
                configMapKeyRef:
                  name: orders-config
                  key: KAFKA_BOOTSTRAP
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"