apiVersion: v1
kind: Secret
metadata:
  name: identity-secrets
  namespace: shopflow
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Server=sql-service.shopflow.svc.cluster.local,1433;Database=ShopFlow.Identity;User Id=sa;Password=Swiss@1991;TrustServerCertificate=True"
  Jwt__Key: "Bpmqwe23@$^5lkj+nxGVY7jfiYX%klIveHFt8pRYw7MtNmLg1hqlcG7J8i1+5HKV9vw"
  Jwt__Issuer: "shopflow.com"
  Jwt__Audience: "shopflow.com"