apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-worker
  namespace: shopflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-worker
  template:
    metadata:
      labels:
        app: notifications-worker
    spec:
      containers:
        - name: notifications-worker
          image: shopflow-notifications:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: notifications-config